import type { LogEvent } from './types';

/** Active alerts table (screen-4). */
export const ALERT_EVENTS: LogEvent[] = [
  {
    id: 'EVT-001',
    time: '03:32',
    date: '11.06.2026',
    type: 'alarm',
    accepted: false,
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-45',
    sensor: 'O2-Б45-вх',
    msg: 'Критически низкий O₂: 5.9 мг/л',
    threshold: '< 7.0',
    value: '5.9 мг/л',
  },
  {
    id: 'EVT-002',
    time: '03:29',
    date: '11.06.2026',
    type: 'alarm',
    accepted: false,
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-03',
    sensor: 'Насос НС-03',
    msg: 'Насос НС-03 — авария',
    threshold: '—',
    value: 'Связь потеряна',
  },
  {
    id: 'EVT-003',
    time: '03:21',
    date: '11.06.2026',
    type: 'alarm',
    accepted: false,
    site: 'Дарг Кох',
    group: 'ДК-1',
    basin: '—',
    sensor: 'T-07',
    msg: 'Нет связи с датчиком T-07',
    threshold: '—',
    value: 'Offline',
  },
  {
    id: 'EVT-004',
    time: '02:47',
    date: '11.06.2026',
    type: 'warn',
    accepted: true,
    site: '5 Озеро',
    group: 'A_76–100',
    basin: 'Б-89',
    sensor: 'O2-Б89-вх',
    msg: 'Низкий O₂: 7.8 мг/л',
    threshold: '< 8.0',
    value: '7.8 мг/л',
    acceptedBy: 'Иванов А.',
    acceptedAt: '02:51',
  },
  {
    id: 'EVT-005',
    time: '02:15',
    date: '11.06.2026',
    type: 'warn',
    accepted: true,
    site: '5 Озеро',
    group: 'A_51–75',
    basin: 'Б-67',
    sensor: 'O2-Б67-вх',
    msg: 'Низкий O₂: 7.4 мг/л',
    threshold: '< 8.0',
    value: '7.4 мг/л',
    acceptedBy: 'Иванов А.',
    acceptedAt: '02:20',
  },
  {
    id: 'EVT-006',
    time: '01:58',
    date: '11.06.2026',
    type: 'warn',
    accepted: true,
    site: 'Ардон',
    group: 'АД-2',
    basin: 'Б-22',
    sensor: 'pH-Б22',
    msg: 'pH ниже нормы: 6.3',
    threshold: '< 6.5',
    value: '6.3',
    acceptedBy: 'Петров В.',
    acceptedAt: '02:05',
  },
  {
    id: 'EVT-007',
    time: '01:30',
    date: '11.06.2026',
    type: 'warn',
    accepted: true,
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-12',
    sensor: 'O2-Б12-вх',
    msg: 'Низкий O₂: 7.1 мг/л',
    threshold: '< 8.0',
    value: '7.1 мг/л',
    acceptedBy: 'Иванов А.',
    acceptedAt: '01:35',
  },
  {
    id: 'EVT-008',
    time: '00:44',
    date: '11.06.2026',
    type: 'service',
    accepted: true,
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-12',
    sensor: 'O2-Б12-out',
    msg: 'Датчик O2-12-out переведён в сервис',
    threshold: '—',
    value: 'Сервис',
    acceptedBy: 'Петров В.',
    acceptedAt: '00:44',
  },
  {
    id: 'EVT-009',
    time: '00:15',
    date: '11.06.2026',
    type: 'service',
    accepted: true,
    site: '5 Озеро',
    group: 'A_76–100',
    basin: 'Б-78',
    sensor: 'T-Б78',
    msg: 'Плановая проверка датчика T-Б78',
    threshold: '—',
    value: 'Сервис',
    acceptedBy: 'Система',
    acceptedAt: '00:15',
  },
  {
    id: 'EVT-010',
    time: '23:50',
    date: '10.06.2026',
    type: 'warn',
    accepted: true,
    site: 'Дарг Кох',
    group: 'ДК-2',
    basin: 'Б-18',
    sensor: 'NH4-Б18',
    msg: 'NH4 выше нормы: 0.09 мг/л',
    threshold: '> 0.08',
    value: '0.09 мг/л',
    acceptedBy: 'Иванов А.',
    acceptedAt: '23:55',
  },
];
