import type { LogEvent } from './types';

/** Full event journal (screen-5). */
export const JOURNAL_EVENTS: LogEvent[] = [
  {
    id: 'EVT-001',
    date: '11.06.2026',
    time: '03:32',
    type: 'alarm',
    site: 'Карджин',
    group: 'A_51–75',
    basin: 'Б-32',
    sensor: 'T-Б32',
    msg: 'Критически низкий O₂: 6.4 мг/л',
    value: '7.7 мг/л',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '03:46',
  },
  {
    id: 'EVT-002',
    date: '11.06.2026',
    time: '03:21',
    type: 'alarm',
    site: 'Дарг Кох',
    group: 'КГ-1',
    basin: 'Б-65',
    sensor: 'O2-Б65-вх',
    msg: 'Нет связи с датчиком T-07',
    value: '8.8 мг/л',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '03:40',
  },
  {
    id: 'EVT-003',
    date: '11.06.2026',
    time: '03:10',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_26–50',
    basin: 'Б-90',
    sensor: 'pH-Б90',
    msg: 'Низкий O₂: 7.2 мг/л',
    value: '9.9',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '03:09',
  },
  {
    id: 'EVT-004',
    date: '11.06.2026',
    time: '02:54',
    type: 'warn',
    site: 'Дарг Кох',
    group: 'ДК-1',
    basin: 'Б-46',
    sensor: 'pH-Б46',
    msg: 'NH4 выше нормы: 0.112 мг/л',
    value: '0.112',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '02:56',
  },
  {
    id: 'EVT-005',
    date: '11.06.2026',
    time: '02:28',
    type: 'alarm',
    site: 'Ардон',
    group: 'АД-3',
    basin: 'Б-25',
    sensor: 'O2-Б25-вх',
    msg: 'Нет связи с датчиком O2-Б25-вх',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '02:42',
  },
  {
    id: 'EVT-006',
    date: '11.06.2026',
    time: '02:06',
    type: 'service',
    site: '5 Озеро',
    group: 'A_76–100',
    basin: 'Б-36',
    sensor: 'pH-Б36',
    msg: 'Плановая проверка датчика pH-Б36',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '02:17',
  },
  {
    id: 'EVT-007',
    date: '11.06.2026',
    time: '01:41',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_26–50',
    basin: 'Б-69',
    sensor: 'T-Б69',
    msg: 'Низкий O₂: 7.4 мг/л',
    value: '7.4 мг/л',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '01:52',
  },
  {
    id: 'EVT-008',
    date: '11.06.2026',
    time: '01:13',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_26–50',
    basin: 'Б-05',
    sensor: 'NH4-Б05',
    msg: 'NH4 выше нормы: 0.091 мг/л',
    value: '0.091',
    accepted: true,
    acceptedBy: 'Сидоров Н.',
    acceptedAt: '01:17',
  },
  {
    id: 'EVT-009',
    date: '11.06.2026',
    time: '00:34',
    type: 'warn',
    site: 'Дарг Кох',
    group: 'ДК-2',
    basin: 'Б-19',
    sensor: 'T-Б19',
    msg: 'pH ниже нормы: 6.1',
    value: '6.1',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '00:49',
  },
  {
    id: 'EVT-010',
    date: '11.06.2026',
    time: '00:01',
    type: 'service',
    site: 'Ардон',
    group: 'АД-1',
    basin: 'Б-18',
    sensor: 'NH4-Б18',
    msg: 'Кормушка переведена в сервис',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '00:04',
  },
  {
    id: 'EVT-011',
    date: '10.06.2026',
    time: '23:43',
    type: 'warn',
    site: 'Дарг Кох',
    group: 'ДК-1',
    basin: 'Б-50',
    sensor: 'NH4-Б50',
    msg: 'Температура выше нормы: 10.1 °C',
    value: '10.1',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '23:54',
  },
  {
    id: 'EVT-012',
    date: '10.06.2026',
    time: '23:18',
    type: 'warn',
    site: 'Ардон',
    group: 'АД-1',
    basin: 'Б-38',
    sensor: 'T-Б38',
    msg: 'Температура выше нормы: 10.0 °C',
    value: '10.0',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '23:27',
  },
  {
    id: 'EVT-013',
    date: '10.06.2026',
    time: '23:04',
    type: 'ok',
    site: 'Ардон',
    group: 'АД-3',
    basin: 'Б-65',
    sensor: 'T-Б65',
    msg: 'O₂ вернулся в норму: 8.2 мг/л',
    value: '8.2 мг/л',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '23:14',
  },
  {
    id: 'EVT-014',
    date: '10.06.2026',
    time: '22:36',
    type: 'warn',
    site: 'Дарг Кох',
    group: 'ДК-1',
    basin: 'Б-15',
    sensor: 'pH-Б15',
    msg: 'NH4 выше нормы: 0.09 мг/л',
    value: '0.09',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '22:38',
  },
  {
    id: 'EVT-015',
    date: '10.06.2026',
    time: '21:57',
    type: 'ok',
    site: '5 Озеро',
    group: 'A_26–50',
    basin: 'Б-17',
    sensor: 'NH4-Б17',
    msg: 'Авария снята оператором',
    value: '—',
    accepted: true,
    acceptedBy: 'Сидоров Н.',
    acceptedAt: '22:06',
  },
  {
    id: 'EVT-016',
    date: '10.06.2026',
    time: '21:22',
    type: 'warn',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-92',
    sensor: 'NH4-Б92',
    msg: 'pH ниже нормы: 6.4',
    value: '6.4',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '21:24',
  },
  {
    id: 'EVT-017',
    date: '10.06.2026',
    time: '20:59',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-44',
    sensor: 'T-Б44',
    msg: 'Критически низкий O₂: 6.3 мг/л',
    value: '6.3 мг/л',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '',
  },
  {
    id: 'EVT-018',
    date: '10.06.2026',
    time: '20:37',
    type: 'alarm',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-43',
    sensor: 'T-Б43',
    msg: 'Нет связи с датчиком T-Б43',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '20:46',
  },
  {
    id: 'EVT-019',
    date: '10.06.2026',
    time: '20:21',
    type: 'warn',
    site: 'Дарг Кох',
    group: 'ДК-1',
    basin: 'Б-61',
    sensor: 'T-Б61',
    msg: 'Температура выше нормы: 9.7 °C',
    value: '9.7',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '20:29',
  },
  {
    id: 'EVT-020',
    date: '10.06.2026',
    time: '20:10',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-52',
    sensor: 'O2-Б52-вх',
    msg: 'NH4 выше нормы: 0.09 мг/л',
    value: '0.09',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '20:17',
  },
  {
    id: 'EVT-021',
    date: '10.06.2026',
    time: '19:51',
    type: 'alarm',
    site: 'Ардон',
    group: 'АД-2',
    basin: 'Б-32',
    sensor: 'NH4-Б32',
    msg: 'Нет связи с датчиком NH4-Б32',
    value: '—',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '',
  },
  {
    id: 'EVT-022',
    date: '10.06.2026',
    time: '19:38',
    type: 'service',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-53',
    sensor: 'NH4-Б53',
    msg: 'Плановая проверка датчика NH4-Б53',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '19:41',
  },
  {
    id: 'EVT-023',
    date: '10.06.2026',
    time: '19:06',
    type: 'service',
    site: '5 Озеро',
    group: 'A_76–100',
    basin: 'Б-34',
    sensor: 'pH-Б34',
    msg: 'Плановая проверка датчика pH-Б34',
    value: '—',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '19:09',
  },
  {
    id: 'EVT-024',
    date: '10.06.2026',
    time: '18:46',
    type: 'ok',
    site: 'Ардон',
    group: 'АД-1',
    basin: 'Б-08',
    sensor: 'O2-Б08-вх',
    msg: 'O₂ вернулся в норму: 9.1 мг/л',
    value: '9.1 мг/л',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '18:56',
  },
  {
    id: 'EVT-025',
    date: '10.06.2026',
    time: '18:08',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-66',
    sensor: 'T-Б66',
    msg: 'Нет связи с датчиком T-Б66',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '18:15',
  },
  {
    id: 'EVT-026',
    date: '10.06.2026',
    time: '17:53',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-80',
    sensor: 'NH4-Б80',
    msg: 'Нет связи с датчиком NH4-Б80',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '18:04',
  },
  {
    id: 'EVT-027',
    date: '10.06.2026',
    time: '17:25',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-51',
    sensor: 'pH-Б51',
    msg: 'Насос НС-12 — авария',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '17:26',
  },
  {
    id: 'EVT-028',
    date: '10.06.2026',
    time: '16:48',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-69',
    sensor: 'pH-Б69',
    msg: 'Низкий O₂: 7.1 мг/л',
    value: '7.1 мг/л',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '16:54',
  },
  {
    id: 'EVT-029',
    date: '10.06.2026',
    time: '16:22',
    type: 'warn',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-70',
    sensor: 'O2-Б70-вх',
    msg: 'pH ниже нормы: 6.27',
    value: '6.27',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '16:37',
  },
  {
    id: 'EVT-030',
    date: '10.06.2026',
    time: '16:06',
    type: 'service',
    site: 'Ардон',
    group: 'АД-1',
    basin: 'Б-14',
    sensor: 'T-Б14',
    msg: 'Кормушка переведена в сервис',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '16:18',
  },
  {
    id: 'EVT-031',
    date: '10.06.2026',
    time: '15:37',
    type: 'service',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-65',
    sensor: 'pH-Б65',
    msg: 'Плановая проверка датчика pH-Б65',
    value: '—',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '',
  },
  {
    id: 'EVT-032',
    date: '10.06.2026',
    time: '15:12',
    type: 'alarm',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-43',
    sensor: 'pH-Б43',
    msg: 'Насос НС-03 — авария',
    value: '—',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '15:21',
  },
  {
    id: 'EVT-033',
    date: '10.06.2026',
    time: '15:04',
    type: 'alarm',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-89',
    sensor: 'O2-Б89-вх',
    msg: 'Насос НС-07 — авария',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '15:11',
  },
  {
    id: 'EVT-034',
    date: '10.06.2026',
    time: '14:48',
    type: 'alarm',
    site: '5 Озеро',
    group: 'A_51–75',
    basin: 'Б-47',
    sensor: 'pH-Б47',
    msg: 'Критически низкий O₂: 5.8 мг/л',
    value: '5.8 мг/л',
    accepted: true,
    acceptedBy: 'Сидоров Н.',
    acceptedAt: '15:01',
  },
  {
    id: 'EVT-035',
    date: '10.06.2026',
    time: '14:14',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-21',
    sensor: 'NH4-Б21',
    msg: 'Насос НС-01 — авария',
    value: '—',
    accepted: false,
    acceptedBy: '',
    acceptedAt: '',
  },
  {
    id: 'EVT-036',
    date: '10.06.2026',
    time: '13:40',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-21',
    sensor: 'NH4-Б21',
    msg: 'Нет связи с датчиком NH4-Б21',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '13:44',
  },
  {
    id: 'EVT-037',
    date: '10.06.2026',
    time: '13:03',
    type: 'warn',
    site: 'Ардон',
    group: 'АД-2',
    basin: 'Б-30',
    sensor: 'O2-Б30-вх',
    msg: 'Низкий O₂: 7.6 мг/л',
    value: '7.6 мг/л',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '13:16',
  },
  {
    id: 'EVT-038',
    date: '10.06.2026',
    time: '12:38',
    type: 'warn',
    site: 'Ардон',
    group: 'АД-3',
    basin: 'Б-66',
    sensor: 'pH-Б66',
    msg: 'Температура выше нормы: 10.4 °C',
    value: '10.4',
    accepted: true,
    acceptedBy: 'Сидоров Н.',
    acceptedAt: '12:41',
  },
  {
    id: 'EVT-039',
    date: '10.06.2026',
    time: '12:14',
    type: 'warn',
    site: '5 Озеро',
    group: 'A_01–25',
    basin: 'Б-77',
    sensor: 'pH-Б77',
    msg: 'Температура выше нормы: 10.3 °C',
    value: '10.3',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '12:21',
  },
  {
    id: 'EVT-040',
    date: '10.06.2026',
    time: '11:54',
    type: 'warn',
    site: 'Ардон',
    group: 'АД-1',
    basin: 'Б-91',
    sensor: 'O2-Б91-вх',
    msg: 'Температура выше нормы: 10.1 °C',
    value: '10.1',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '12:05',
  },
  {
    id: 'EVT-041',
    date: '10.06.2026',
    time: '11:25',
    type: 'warn',
    site: 'Ардон',
    group: 'АД-3',
    basin: 'Б-16',
    sensor: 'pH-Б16',
    msg: 'pH ниже нормы: 6.27',
    value: '6.27',
    accepted: true,
    acceptedBy: 'Сидоров Н.',
    acceptedAt: '11:34',
  },
  {
    id: 'EVT-042',
    date: '10.06.2026',
    time: '11:09',
    type: 'warn',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-86',
    sensor: 'T-Б86',
    msg: 'Температура выше нормы: 10.2 °C',
    value: '10.2',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '11:14',
  },
  {
    id: 'EVT-043',
    date: '10.06.2026',
    time: '10:43',
    type: 'ok',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-75',
    sensor: 'pH-Б75',
    msg: 'O₂ вернулся в норму: 8.7 мг/л',
    value: '8.7 мг/л',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '10:52',
  },
  {
    id: 'EVT-044',
    date: '10.06.2026',
    time: '10:05',
    type: 'service',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-37',
    sensor: 'pH-Б37',
    msg: 'Кормушка переведена в сервис',
    value: '—',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '10:16',
  },
  {
    id: 'EVT-045',
    date: '10.06.2026',
    time: '09:38',
    type: 'alarm',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-19',
    sensor: 'O2-Б19-вх',
    msg: 'Критически низкий O₂: 5.8 мг/л',
    value: '5.8 мг/л',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '09:46',
  },
  {
    id: 'EVT-046',
    date: '10.06.2026',
    time: '09:04',
    type: 'warn',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-64',
    sensor: 'T-Б64',
    msg: 'Температура выше нормы: 9.7 °C',
    value: '9.7',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '09:17',
  },
  {
    id: 'EVT-047',
    date: '10.06.2026',
    time: '08:29',
    type: 'service',
    site: 'Карджин',
    group: 'КГ-1',
    basin: 'Б-90',
    sensor: 'NH4-Б90',
    msg: 'Кормушка переведена в сервис',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '08:37',
  },
  {
    id: 'EVT-048',
    date: '10.06.2026',
    time: '08:13',
    type: 'service',
    site: 'Дарг Кох',
    group: 'ДК-2',
    basin: 'Б-97',
    sensor: 'NH4-Б97',
    msg: 'Плановая проверка датчика NH4-Б97',
    value: '—',
    accepted: true,
    acceptedBy: 'Система',
    acceptedAt: '08:21',
  },
  {
    id: 'EVT-049',
    date: '10.06.2026',
    time: '07:49',
    type: 'service',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-99',
    sensor: 'NH4-Б99',
    msg: 'Кормушка переведена в сервис',
    value: '—',
    accepted: true,
    acceptedBy: 'Иванов А.',
    acceptedAt: '08:01',
  },
  {
    id: 'EVT-050',
    date: '10.06.2026',
    time: '07:23',
    type: 'warn',
    site: 'Карджин',
    group: 'КГ-2',
    basin: 'Б-43',
    sensor: 'O2-Б43-вх',
    msg: 'NH4 выше нормы: 0.086 мг/л',
    value: '0.086',
    accepted: true,
    acceptedBy: 'Петров В.',
    acceptedAt: '07:35',
  },
];
